from prompt_template import metaprompt
from gemini_api import generate_text


def enhance_prompt(raw_prompt):
    """
    Enhances the raw user prompt using Gemini and the metaprompt.

    Args:
        raw_prompt (str): The user's original prompt.

    Returns:
        str: The enhanced prompt generated by Gemini.
    """

    final_prompt = metaprompt.replace("{{TASK}}", raw_prompt)
    enhanced_prompt = generate_text(final_prompt)
    return enhanced_prompt